# Generated by Django 5.1.1 on 2024-09-20 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('posiciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='fotos_jugadores/')),
                ('fecha_nacimiento', models.DateField()),
                ('numero_camiseta', models.IntegerField()),
                ('titular', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.teams')),
                ('posicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posiciones.positions')),
            ],
        ),
    ]
