# Generated by Django 5.1.1 on 2024-09-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('suramerica', 'suramerica'), ('centroamerica', 'centroamerica'), ('norteamerica', 'norteamerica'), ('europa', 'europa'), ('africa', 'africa'), ('medio oriente', 'medio oriente'), ('oseania', 'oseania')], max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
