# Generated by Django 5.1.1 on 2024-09-20 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bandera', models.ImageField(upload_to='banderas/')),
                ('escudo', models.ImageField(upload_to='escudos/')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='categorias.continente')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
                'ordering': ['id'],
            },
        ),
    ]
